[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#F6FAFD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
